CREATE DATABASE COIN;

CREATE TABLE IF NOT EXISTS CURRENCY_PAIR (
    ID BIGINT(100) NOT NULL AUTO_INCREMENT,
    EXCHANGE_NAME VARCHAR(50),
    NAME VARCHAR(100),
    DATETIME TIMESTAMP,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS ASKS (
    ID BIGINT(100) NOT NULL AUTO_INCREMENT,
    PRICE VARCHAR(20),
    QUANTITY VARCHAR(20),
    VALUE DECIMAL(20,10),
    CURRENCY_PAIR_ID BIGINT(100),
    PRIMARY KEY (ID),
    FOREIGN KEY (CURRENCY_PAIR_ID) REFERENCES CURRENCY_PAIR(ID)
);

CREATE TABLE IF NOT EXISTS BIDS (
    ID BIGINT(100) NOT NULL AUTO_INCREMENT,
    PRICE VARCHAR(20),
    QUANTITY VARCHAR(20),
    VALUE DECIMAL(20,10),
    CURRENCY_PAIR_ID BIGINT(100),
    PRIMARY KEY (ID),
    FOREIGN KEY (CURRENCY_PAIR_ID) REFERENCES CURRENCY_PAIR(ID)
);

